image:
  repository: ghost
  tag: "5"

mysql:
  image: mysql:8.0

storage:
  size: 1Gi
  storageClass: longhorn   # ✅ added for Longhorn support

database:
  mysql:
    rootPassword: rootpass
    database: ghost
    user: ghost
    password: ghostpass

resources:
  ghost:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  mysql:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

labels:
  organization: default-org
  environment: production
  appType: ghost_mysql
  region: in-central

ingress:
  enabled: true
  hosts:
    - host: #Add Domain
  tls:
    - secretName: #Add Domain
      hosts:
        -  #Add Domain
