image:
  repository: ghost
  tag: "5"

mysql:
  image: mysql:8.0

storage:
  size: 1Gi

database:
  mysql:
    rootPassword: rootpass
    database: ghost
    user: ghost
    password: ghostpass

labels:
  organization: default-org
  environment: production
  appType: ghost_mysql
  region: in-central

ingress:
  enabled: true
  hosts:
    - host: #Add Domain
  tls:
    - secretName: #Add Domain
      hosts:
        -  #Add Domain
