image:
  wordpress:
    repository: wordpress
    tag: "latest"
  mysql:
    repository: mysql
    tag: "8.0"

storage:
  size: 2Gi
  storageClass: local-path  

database:
  mysql:
    db: wordpress
    user: wordpress
    password: wordpress
    rootPassword: rootpassword
    host: 127.0.0.1
    port: 3306

resources:
  wordpress:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  mysql:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

labels:
  organization: default-org
  environment: production
  appType: wordpress
  region: in-central

ingress:
  enabled: true
  hosts:
    - host: ""   # replace with your domain
  tls:
    - secretName: your-domain-tls
      hosts:
        - ""
