apiVersion: apps/v1
kind: Deployment
metadata:
  name: listmonk-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listmonk-postgres
  template:
    metadata:
      labels:
        app: listmonk-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.database.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.postgres.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.database.postgres.db | quote }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U {{ .Values.database.postgres.user }} -d {{ .Values.database.postgres.db }}
            initialDelaySeconds: 10
            periodSeconds: 10

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: listmonk-postgres-pvc
