apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: listmonk-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: 5Gi
