apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "listmonk.fullname" . }}-listmonk
  labels:
    {{- include "listmonk.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.listmonkSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "listmonk.fullname" . }}-postgres
  labels:
    {{- include "listmonk.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.postgresSize }}
