apiVersion: v1
kind: Secret
metadata:
  name: {{ include "listmonk.fullname" . }}-secret
  labels:
    {{- include "listmonk.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-root-password: {{ .Values.database.rootPassword | b64enc | quote }}
  postgres-password: {{ .Values.database.password | b64enc | quote }}
  LISTMONK_db__password: {{ .Values.database.password | b64enc | quote }}
