apiVersion: v1
kind: Service
metadata:
  name: {{ include "listmonk.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "listmonk.fullname" . }}
  ports:
    - port: 80
      targetPort: 9000
