apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ghost.fullname" . }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ghost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ghost.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: ghost
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          resources:
            requests:
              cpu: {{ .Values.ghost.resources.requests.cpu }}
              memory: {{ .Values.ghost.resources.requests.memory }}
            limits:
              cpu: {{ .Values.ghost.resources.limits.cpu }}
              memory: {{ .Values.ghost.resources.limits.memory }}
          env:
            - name: url
              value: "https://{{ (index .Values.ingress.hosts 0).host | default "example.com" }}"
            - name: database__client
              value: {{ .Values.database.client | quote }}
            - name: database__connection__filename
              value: {{ .Values.database.connection.filename | quote }}
            - name: NODE_ENV
              value: {{ .Values.ghost.nodeEnv | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.ghost.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          volumeMounts:
            - name: ghost-data
              mountPath: /var/lib/ghost/content
            - name: ghost-config
              mountPath: /var/lib/ghost/config.production.json
              subPath: config.production.json
      volumes:
        - name: ghost-data
          persistentVolumeClaim:
            claimName: {{ include "ghost.fullname" . }}-pvc
        - name: ghost-config
          configMap:
            name: {{ include "ghost.fullname" . }}-config
