apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ghost.fullname" . }}-pvc
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
