apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ghost.fullname" . }}-pvc
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce  # Use ReadWriteMany only if Longhorn RWX is enabled
  resources:
    requests:
      storage: {{ .Values.storage.size | default "1Gi" }}
  storageClassName: longhorn
  volumeMode: Filesystem
