apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghost.fullname" . }}-service
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "ghost.fullname" . }}
  ports:
    - port: 80
      targetPort: 2368