image:
  repository: listmonk/listmonk
  tag: "latest"

storage:
  size: 5Gi
  storageClass: longhorn

database:
  postgres:
    db: listmonk
    user: listmonk
    password: supersecurepassword
    host: 127.0.0.1
    port: 5432

resources:
  listmonk:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  postgres:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

labels:
  organization: default-org
  environment: production
  appType: listmonk
  region: in-central

ingress:
  enabled: true
  hosts:
    - host: ""
  tls:
    - secretName: ""
