apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-secret
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.database.mysql.rootPassword | b64enc | quote }}
  mysql-password: {{ .Values.database.mysql.password | b64enc | quote }}
  wordpress-db-password: {{ .Values.database.mysql.password | b64enc | quote }}
