# --- MySQL PVC ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mattermost.fullname" . }}-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.storageClass }}

---
# --- Mattermost PVC ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mattermost.fullname" . }}-mattermost-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.storageClass }}
