---
# Mattermost Data PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mattermost.fullname" . }}-mattermost
  labels:
    {{- include "mattermost.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.mattermostSize }}
---
# MySQL Data PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mattermost.fullname" . }}-mysql
  labels:
    {{- include "mattermost.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.mysqlSize }}
