apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "whatomate.fullname" . }}-uploads
  labels:
    {{- include "whatomate.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
