apiVersion: v1
kind: Secret
metadata:
  name: {{ include "whatomate.fullname" . }}-secret
  labels:
    {{- include "whatomate.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.database.password | default "changeme" | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | default "" | b64enc | quote }}
  JWT_SECRET: {{ .Values.jwt.secret | default "changeme" | b64enc | quote }}
  ENCRYPTION_KEY: {{ .Values.appConfig.encryptionKey | default "" | b64enc | quote }}
