apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ghost.fullname" . }}-config
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
data:
  config.production.json: |
    {
      "url": "https://{{ (index .Values.ingress.hosts 0).host }}",
      "server": {
        "port": {{ .Values.ghost.port }},
        "host": "0.0.0.0"
      },
      "database": {
        "client": "mysql",
        "connection": {
          "host": "127.0.0.1",
          "port": {{ .Values.mysql.port }},
          "user": "{{ .Values.database.mysql.user }}",
          "database": "{{ .Values.database.mysql.database }}"
        }
      },
      "logging": {
        "level": "info"
      }
    }
