apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ghost.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "ghost.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "ghost.fullname" . }}
        orgname: {{ .Values.labels.organization }}
    spec:
      containers:
        # --- MYSQL SIDE CAR ---
        - name: mysql
          image: {{ .Values.mysql.image }}
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.database.mysql.rootPassword | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.database.mysql.database | quote }}
            - name: MYSQL_USER
              value: {{ .Values.database.mysql.user | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.database.mysql.password | quote }}
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: ghost-data
              mountPath: /var/lib/mysql
              subPath: mysql

        # --- GHOST CONTAINER ---
        - name: ghost
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: database__client
              value: "mysql"
            - name: database__connection__host
              value: "127.0.0.1"
            - name: database__connection__user
              value: {{ .Values.database.mysql.user | quote }}
            - name: database__connection__password
              value: {{ .Values.database.mysql.password | quote }}
            - name: database__connection__database
              value: {{ .Values.database.mysql.database | quote }}
            - name: database__connection__port
              value: "3306"
            - name: database__connection__reconnect
              value: "true"
            - name: url
              value: "https://{{ (index .Values.ingress.hosts 0).host }}"
            - name: NODE_ENV
              value: "production"
          ports:
            - containerPort: 2368
          volumeMounts:
            - name: ghost-data
              mountPath: /var/lib/ghost/content
              subPath: ghost
      volumes:
        - name: ghost-data
          persistentVolumeClaim:
            claimName: {{ include "ghost.fullname" . }}-pvc
