---
# -- Replica count
replicaCount: 1

image:
  repository: mattermost/mattermost-team-edition
  tag: "9.5"
  pullPolicy: IfNotPresent

# -- Mattermost specific configuration
mattermost:
  port: 8065
  nodeEnv: production
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

# -- MySQL database configuration
mysql:
  image: mysql:8.0
  port: 3306
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

# -- Database configuration
database:
  client: mysql
  mysql:
    database: mattermost
    user: mmuser
    password: ""  # Set via Kubernetes Secret
    rootPassword: ""  # Set via Kubernetes Secret

# -- Storage configuration
storage:
  mattermostSize: 10Gi
  mysqlSize: 20Gi
  storageClass: longhorn

# -- Standard Kubernetes labels
labels:
  organization: default-org
  environment: production
  appType: mattermost_mysql
  region: in-central

# -- Ingress configuration
ingress:
  enabled: true
  hosts:
    - host: #Add Domain
  tls:
    - secretName: #Add Domain
      hosts:
        -  #Add Domain

# -- Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 8065

# -- ServiceAccount configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""

# -- Pod annotations
podAnnotations: {}

# -- Pod security context
podSecurityContext: {}

# -- Security context for containers
securityContext: {}
