image:
  repository: mattermost/mattermost-team-edition
  tag: "9.5"

storage:
  size: 10Gi
  storageClass: longhorn  
database:
  client: mysql
  mysql:
    database: mattermost
    user: mmuser
    password: strongpassword
    rootPassword: rootstrongpassword

resources:
  mattermost:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  mysql:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

labels:
  organization: default-org
  environment: production
  appType: mattermost_mysql_single_pod
  region: in-central

ingress:
  enabled: true
  hosts:
    - host: ""
  tls:
    - secretName: ""
